# SUPPORT VECTOR MACHINE

In [29]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set

In [30]:
train = pd.read_csv(r"C:\Users\saiha\OneDrive\Documents\Python\APPLIEDDATASCIENCEwithPYTHON\ML\train.csv")
test = pd.read_csv(r"C:\Users\saiha\OneDrive\Documents\Python\APPLIEDDATASCIENCEwithPYTHON\ML\test.csv")

In [31]:
train.head(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

## FEATURE ENGINEERING

In [32]:
train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [33]:
train.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [34]:
print(train.shape, test.shape)

(891, 12) (418, 11)

In [35]:
train['data'] = 'train'
test['data'] = 'test'
# creating a new column named data and filling train in train dataset and test in test dataset

In [36]:
train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'data'],
      dtype='object')

In [37]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  data         891 non-null    object
dtypes: float64(2), int64(5), object(6)
memory usage: 90.6+ KB

In [38]:
train['data'].head(3)

0    train
1    train
2    train
Name: data, dtype: object

In [39]:
train.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
data             0
dtype: int64

In [40]:
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
data             0
dtype: int64

In [41]:
test_passenger_id = test['PassengerId']
# storing passengeid from test dataset to new dataset

In [42]:
dataset = pd.concat([train, test], axis = 0)
# combining train and test
#axis = 0  --> is concatination on rows
#axis = 1 -->  about columns
dataset

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,data
0,1,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,train
1,2,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,train
2,3,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,train
3,4,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,train
4,5,0.0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,NaN,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,test
414,1306,NaN,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,test
415,1307,NaN,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,test
416,1308,NaN,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,test
417,1309,NaN,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,test

In [43]:
dataset.shape

(1309, 13)

In [44]:
dataset.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,data
413,1305,NaN,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,test
414,1306,NaN,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,test
415,1307,NaN,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,test
416,1308,NaN,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,test
417,1309,NaN,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,test

In [45]:
dataset.isna().sum()/len(dataset)*100

PassengerId     0.000000
Survived       31.932773
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            20.091673
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.076394
Cabin          77.463713
Embarked        0.152788
data            0.000000
dtype: float64

In [46]:
dataset = dataset.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis = 1)

# cabin has lot of null values and the others are not significant for survival rate

In [47]:
dataset.isna().sum()

Survived    418
Pclass        0
Sex           0
Age         263
SibSp         0
Parch         0
Fare          1
Embarked      2
data          0
dtype: int64

In [48]:
dataset['Age'] = dataset['Age'].fillna(dataset['Age'].median())

In [49]:
dataset['Embarked'].value_counts()

Embarked
S    914
C    270
Q    123
Name: count, dtype: int64

In [50]:
dataset['Embarked'] = dataset['Embarked'].fillna('S')

In [51]:
dataset['Fare'] = dataset.groupby('Pclass')['Fare'].transform(lambda x : x.fillna(x.median()))
# cuz the Pclasses are different, so there medians will be different too

In [52]:
dataset['Fare'].head()

0     7.2500
1    71.2833
2     7.9250
3    53.1000
4     8.0500
Name: Fare, dtype: float64

In [53]:
dataset['Fare'].nunique()

281

In [54]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1309 entries, 0 to 417
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    float64
 1   Pclass    1309 non-null   int64
 2   Sex       1309 non-null   object
 3   Age       1309 non-null   float64
 4   SibSp     1309 non-null   int64
 5   Parch     1309 non-null   int64
 6   Fare      1309 non-null   float64
 7   Embarked  1309 non-null   object
 8   data      1309 non-null   object
dtypes: float64(3), int64(3), object(3)
memory usage: 102.3+ KB

In [55]:
dataset.isna().sum()

Survived    418
Pclass        0
Sex           0
Age           0
SibSp         0
Parch         0
Fare          0
Embarked      0
data          0
dtype: int64

In [56]:
dataset = pd.get_dummies(dataset, columns = ['Sex', 'Embarked', 'Pclass'], drop_first = True)

In [57]:
dataset.head()

,Survived,Age,SibSp,Parch,Fare,data,Sex_male,Embarked_Q,Embarked_S,Pclass_2,Pclass_3
0,0.0,22.0,1,0,7.2500,train,True,False,True,False,True
1,1.0,38.0,1,0,71.2833,train,False,False,False,False,False
2,1.0,26.0,0,0,7.9250,train,False,False,True,False,True
3,1.0,35.0,1,0,53.1000,train,False,False,True,False,False
4,0.0,35.0,0,0,8.0500,train,True,False,True,False,True

In [61]:
train = dataset[dataset['data'] == 'train']
test = dataset[dataset['data'] == 'test']
# train and test variable will only contain data which have train and test observation respectively
# this is called Boolean Indexing or Boolean Filtering

In [62]:
train

,Survived,Age,SibSp,Parch,Fare,data,Sex_male,Embarked_Q,Embarked_S,Pclass_2,Pclass_3
0,0.0,22.0,1,0,7.2500,train,True,False,True,False,True
1,1.0,38.0,1,0,71.2833,train,False,False,False,False,False
2,1.0,26.0,0,0,7.9250,train,False,False,True,False,True
3,1.0,35.0,1,0,53.1000,train,False,False,True,False,False
4,0.0,35.0,0,0,8.0500,train,True,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...
886,0.0,27.0,0,0,13.0000,train,True,False,True,True,False
887,1.0,19.0,0,0,30.0000,train,False,False,True,False,False
888,0.0,28.0,1,2,23.4500,train,False,False,True,False,True
889,1.0,26.0,0,0,30.0000,train,True,False,False,False,False
890,0.0,32.0,0,0,7.7500,train,True,True,False,False,True

In [63]:
test

,Survived,Age,SibSp,Parch,Fare,data,Sex_male,Embarked_Q,Embarked_S,Pclass_2,Pclass_3
0,NaN,34.5,0,0,7.8292,test,True,True,False,False,True
1,NaN,47.0,1,0,7.0000,test,False,False,True,False,True
2,NaN,62.0,0,0,9.6875,test,True,True,False,True,False
3,NaN,27.0,0,0,8.6625,test,True,False,True,False,True
4,NaN,22.0,1,1,12.2875,test,False,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...
413,NaN,28.0,0,0,8.0500,test,True,False,True,False,True
414,NaN,39.0,0,0,108.9000,test,False,False,False,False,False
415,NaN,38.5,0,0,7.2500,test,True,False,True,False,True
416,NaN,28.0,0,0,8.0500,test,True,False,True,False,True
417,NaN,28.0,1,1,22.3583,test,True,False,False,False,True

In [65]:
print(train.shape, test.shape)

(891, 11) (418, 11)

In [66]:
test.columns

Index(['Survived', 'Age', 'SibSp', 'Parch', 'Fare', 'data', 'Sex_male',
       'Embarked_Q', 'Embarked_S', 'Pclass_2', 'Pclass_3'],
      dtype='object')

In [67]:
train.columns

Index(['Survived', 'Age', 'SibSp', 'Parch', 'Fare', 'data', 'Sex_male',
       'Embarked_Q', 'Embarked_S', 'Pclass_2', 'Pclass_3'],
      dtype='object')

In [68]:
test[['Survived']]

     Survived
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
413       NaN
414       NaN
415       NaN
416       NaN
417       NaN

[418 rows x 1 columns]

In [69]:
train.head()

,Survived,Age,SibSp,Parch,Fare,data,Sex_male,Embarked_Q,Embarked_S,Pclass_2,Pclass_3
0,0.0,22.0,1,0,7.2500,train,True,False,True,False,True
1,1.0,38.0,1,0,71.2833,train,False,False,False,False,False
2,1.0,26.0,0,0,7.9250,train,False,False,True,False,True
3,1.0,35.0,1,0,53.1000,train,False,False,True,False,False
4,0.0,35.0,0,0,8.0500,train,True,False,True,False,True

In [70]:
train[['Survived']]

     Survived
0         0.0
1         1.0
2         1.0
3         1.0
4         0.0
..        ...
886       0.0
887       1.0
888       0.0
889       1.0
890       0.0

[891 rows x 1 columns]

#### SPLIT THE DATA INTO X AND Y

In [72]:
x = train.drop(['Survived', 'data'], axis = 1)
y = train['Survived']

In [73]:
x.head()

,Age,SibSp,Parch,Fare,Sex_male,Embarked_Q,Embarked_S,Pclass_2,Pclass_3
0,22.0,1,0,7.2500,True,False,True,False,True
1,38.0,1,0,71.2833,False,False,False,False,False
2,26.0,0,0,7.9250,False,False,True,False,True
3,35.0,1,0,53.1000,False,False,True,False,False
4,35.0,0,0,8.0500,True,False,True,False,True

In [74]:
y.head()

0    0.0
1    1.0
2    1.0
3    1.0
4    0.0
Name: Survived, dtype: float64

In [75]:
y.value_counts()

Survived
0.0    549
1.0    342
Name: count, dtype: int64

In [76]:
test.head()

,Survived,Age,SibSp,Parch,Fare,data,Sex_male,Embarked_Q,Embarked_S,Pclass_2,Pclass_3
0,NaN,34.5,0,0,7.8292,test,True,True,False,False,True
1,NaN,47.0,1,0,7.0000,test,False,False,True,False,True
2,NaN,62.0,0,0,9.6875,test,True,True,False,True,False
3,NaN,27.0,0,0,8.6625,test,True,False,True,False,True
4,NaN,22.0,1,1,12.2875,test,False,False,True,False,True

In [77]:
test = test.drop(['Survived', 'data'], axis = 1)

In [78]:
test.head()

,Age,SibSp,Parch,Fare,Sex_male,Embarked_Q,Embarked_S,Pclass_2,Pclass_3
0,34.5,0,0,7.8292,True,True,False,False,True
1,47.0,1,0,7.0000,False,False,True,False,True
2,62.0,0,0,9.6875,True,True,False,True,False
3,27.0,0,0,8.6625,True,False,True,False,True
4,22.0,1,1,12.2875,False,False,True,False,True

In [79]:
test.shape

(418, 9)

#### SPLIT THE DATA INTO TRAIN AND TEST

In [85]:
from sklearn.model_selection import train_test_split as tts

x_train, x_test, y_train, y_test = tts(x, y, test_size = 0.2, stratify = y, random_state = 500)
# stratify ensures that the class distribution in the training and testing sets is similar to the original dataset.
# stratify=y is mainly used for classification tasks. It is generally not used for regression because the target values are continuous rather than belonging to discrete classes.

In [86]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

test = scaler.transform(test)

In [96]:
print(x_train.shape)
print(y_train.shape)

(712, 9)
(712,)

In [100]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x_train, y_train)

print(model.score(x_train, y_train))

# as R2 score is not close to 1, the data in non-linear

0.3834973247064295

## SUPPORT VECTOR MACHINE

In [87]:
from sklearn.svm import SVC

# kernel - linear
svm_linear = SVC(kernel = 'linear')

svm_linear.fit(x_train, y_train)

SVC(kernel='linear')

In [88]:
y_pred_train_linear = svm_linear.predict(x_train)
y_pred_test_linear = svm_linear.predict(x_test)

| Model         | Solves | Kernel Support   | When to Use                  |
| ------------- | ------ | ---------------- | ---------------------------- |
| `SVC()`       | Dual   | Yes              | Small/medium data, nonlinear |
| `LinearSVC()` | Primal | No (linear only) | Large datasets               |

In [89]:
print(y_train.shape)

(712,)

In [90]:
# kernel - sigmoid

svm_sigmoid = SVC(kernel = 'sigmoid')
svm_sigmoid.fit(x_train, y_train)
y_pred_train_sigmoid = svm_sigmoid.predict(x_train)
y_pred_test_sigmoid = svm_sigmoid.predict(x_test)

In [91]:
#kernel - poly
svm_poly = SVC(kernel='poly')
svm_poly.fit(x_train, y_train)
y_pred_train_poly = svm_poly.predict(x_train)
y_pred_test_poly = svm_poly.predict(x_test)

In [92]:
#kernel - rbf
svm_rbf = SVC(kernel='rbf')
svm_rbf.fit(x_train, y_train)
y_pred_train_rbf = svm_rbf.predict(x_train)
y_pred_test_rbf = svm_rbf.predict(x_test)

In [93]:
y_pred_test_rbf

array([0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 1.,
       0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0.,
       0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0.,
       1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1.,
       1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0.,
       0., 0., 0., 1., 0., 1., 0., 1., 1.])

## EVALUATION

In [102]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [103]:
print("Training Accuracy - Linear :", accuracy_score(y_train, y_pred_train_linear))
print("*************"*5)
print("Test Accuracy - Linear :", accuracy_score(y_test, y_pred_test_linear))
print("*************"*5)

Training Accuracy - Linear : 0.7752808988764045
*****************************************************************
Test Accuracy - Linear : 0.8324022346368715
*****************************************************************

In [104]:
print("Training Accuracy - sigmoid :", accuracy_score(y_train, y_pred_train_sigmoid))
print("*************"*5)
print("Test Accuracy - sigmoid :", accuracy_score(y_test, y_pred_test_sigmoid))
print("*************"*5)

Training Accuracy - sigmoid : 0.6460674157303371
*****************************************************************
Test Accuracy - sigmoid : 0.6815642458100558
*****************************************************************

In [105]:
print("Training Accuracy - poly :", accuracy_score(y_train, y_pred_train_poly))
print("*************"*5)
print("Test Accuracy - poly :", accuracy_score(y_test, y_pred_test_poly))
print("*************"*5)

Training Accuracy - poly : 0.8286516853932584
*****************************************************************
Test Accuracy - poly : 0.8324022346368715
*****************************************************************

In [106]:
print("Training Accuracy - rbf :", accuracy_score(y_train, y_pred_train_rbf))
print("*************"*5)
print("Test Accuracy - rbf :", accuracy_score(y_test, y_pred_test_rbf))

Training Accuracy - rbf : 0.8342696629213483
*****************************************************************
Test Accuracy - rbf : 0.8547486033519553

In [107]:
print("Training Accuracy - Linear :", classification_report(y_train, y_pred_train_linear))
print("*************"*5)
print("Test Accuracy - Linear :", classification_report(y_test, y_pred_test_linear))

Training Accuracy - Linear :               precision    recall  f1-score   support

         0.0       0.79      0.86      0.83       439
         1.0       0.74      0.64      0.69       273

    accuracy                           0.78       712
   macro avg       0.77      0.75      0.76       712
weighted avg       0.77      0.78      0.77       712

*****************************************************************
Test Accuracy - Linear :               precision    recall  f1-score   support

         0.0       0.90      0.82      0.86       110
         1.0       0.75      0.86      0.80        69

    accuracy                           0.83       179
   macro avg       0.82      0.84      0.83       179
weighted avg       0.84      0.83      0.83       179

In [108]:
print("Training Accuracy - sigmoid :", classification_report(y_train, y_pred_train_sigmoid))
print("*************"*5)
print("Test Accuracy - sigmoid :", classification_report(y_test, y_pred_test_sigmoid))
print("*************"*5)

Training Accuracy - sigmoid :               precision    recall  f1-score   support

         0.0       0.71      0.73      0.72       439
         1.0       0.54      0.52      0.53       273

    accuracy                           0.65       712
   macro avg       0.62      0.62      0.62       712
weighted avg       0.64      0.65      0.64       712

*****************************************************************
Test Accuracy - sigmoid :               precision    recall  f1-score   support

         0.0       0.75      0.72      0.73       110
         1.0       0.58      0.62      0.60        69

    accuracy                           0.68       179
   macro avg       0.67      0.67      0.67       179
weighted avg       0.69      0.68      0.68       179

*****************************************************************

In [109]:
print("Training Accuracy - poly :", classification_report(y_train, y_pred_train_poly))
print("*************"*5)
print("Test Accuracy - poly :", classification_report(y_test, y_pred_test_poly))
print("*************"*5)

Training Accuracy - poly :               precision    recall  f1-score   support

         0.0       0.80      0.96      0.87       439
         1.0       0.91      0.61      0.73       273

    accuracy                           0.83       712
   macro avg       0.86      0.79      0.80       712
weighted avg       0.84      0.83      0.82       712

*****************************************************************
Test Accuracy - poly :               precision    recall  f1-score   support

         0.0       0.84      0.90      0.87       110
         1.0       0.82      0.72      0.77        69

    accuracy                           0.83       179
   macro avg       0.83      0.81      0.82       179
weighted avg       0.83      0.83      0.83       179

*****************************************************************

In [110]:
print("Training Accuracy - rbf :", classification_report(y_train, y_pred_train_rbf))
print("*************"*5)
print("Test Accuracy - rbf :", classification_report(y_test, y_pred_test_rbf))

Training Accuracy - rbf :               precision    recall  f1-score   support

         0.0       0.81      0.96      0.88       439
         1.0       0.91      0.63      0.75       273

    accuracy                           0.83       712
   macro avg       0.86      0.80      0.81       712
weighted avg       0.85      0.83      0.83       712

*****************************************************************
Test Accuracy - rbf :               precision    recall  f1-score   support

         0.0       0.86      0.92      0.89       110
         1.0       0.85      0.75      0.80        69

    accuracy                           0.85       179
   macro avg       0.85      0.84      0.84       179
weighted avg       0.85      0.85      0.85       179

## CROSS VALIDATON METHOD

In [112]:
from sklearn.model_selection import cross_val_score

train_accuracy = cross_val_score(svm_linear, x_train, y_train, cv=10)

print("Training accuracy :", train_accuracy)
print("************"*5)
print("Training Mean Accuracy :", train_accuracy.mean())
print("************"*5)
print("Training Max Accuracy :", train_accuracy.max())
print()
print("*************"*5)
print("Test Accuracy - Linear :", accuracy_score(y_test, y_pred_test_linear))

Training accuracy : [0.79166667 0.86111111 0.71830986 0.76056338 0.73239437 0.8028169
 0.74647887 0.74647887 0.78873239 0.77464789]
************************************************************
Training Mean Accuracy : 0.7723200312989046
************************************************************
Training Max Accuracy : 0.8611111111111112

*****************************************************************
Test Accuracy - Linear : 0.8324022346368715

In [113]:
from sklearn.model_selection import cross_val_score
train_accuracy = cross_val_score(svm_rbf, x_train, y_train, cv=10)

print("Training accuracy :", train_accuracy)
print("************"*5)
print("Training Mean Accuracy :", train_accuracy.mean())
print("************"*5)
print("Training Max Accuracy :", train_accuracy.max())
print()
print("*************"*5)
print("Test Accuracy - RBF :", accuracy_score(y_test, y_pred_test_rbf))

Training accuracy : [0.86111111 0.90277778 0.74647887 0.87323944 0.81690141 0.81690141
 0.83098592 0.76056338 0.81690141 0.8028169 ]
************************************************************
Training Mean Accuracy : 0.8228677621283256
************************************************************
Training Max Accuracy : 0.9027777777777778

*****************************************************************
Test Accuracy - RBF : 0.8547486033519553

# GRID SEARCH CV

In [114]:
from sklearn.model_selection import GridSearchCV as gscv

In [115]:
SVC()

SVC()

In [117]:
param_grid = {'C':[0.1,1,2,10,100], 'gamma':[1,0.1,0.01,0.001]}

grid = gscv(SVC(),param_grid=param_grid,cv = 5, refit=True)
grid.fit(x_train, y_train)
grid_predict = grid.predict(x_test)
print(accuracy_score(y_test, grid_predict))

# Grid Search to find the best hyperparameters for an SVM (Support Vector Machine) model.

# C controls how much the model tries to classify every training point correctly

# Small C
# C = 0.1
# Wider margin
# Allows some mistakes
# Simpler model
# Less overfitting

# Large C
# C = 100
# Tries to classify every point correctly
# Smaller margin
# More complex model
# May overfit

# Gamma controls how far the influence of one training point extends.

# Small Gamma
# gamma = 0.001
# A point influences a large area.
# Decision boundary is smoother

# Large Gamma
# gamma = 1
# Each point influences only a small neighborhood.
# Decision boundary becomes more complex.

0.8491620111731844

In [118]:
final_pred = svm_rbf.predict(test)

In [119]:
final_pred

array([0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0.,
       0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0.,
       0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0.,
       0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0.,
       0., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0.,
       1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0.,
       1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       1., 1., 1., 1., 0., 0., 1., 0., 0., 0.])

In [121]:
np.unique(final_pred, return_counts = True)
# return_counts = True gives the freq of each unique value

array([0., 1.])

In [122]:
len(final_pred)

418

In [123]:
test_df = pd.DataFrame({'PassengerId' : test_passenger_id, 'Survived' : final_pred})

test_df.tail()

     PassengerId  Survived
413         1305       0.0
414         1306       1.0
415         1307       0.0
416         1308       0.0
417         1309       0.0

In [124]:
test_df.head()

   PassengerId  Survived
0          892       0.0
1          893       0.0
2          894       0.0
3          895       0.0
4          896       0.0

In [125]:
test_df.to_csv("submission.csv", index=False)
# Saves the DataFrame to a CSV file without the extra index column.

In [126]:
import os
print(os.getcwd())

C:\Users\saiha\ML